[2025-03-30T10:03:16.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T10:03:16.596+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Lat_Phrao manual__2025-03-30T10:03:09.568060+00:00 [queued]>
[2025-03-30T10:03:16.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Lat_Phrao manual__2025-03-30T10:03:09.568060+00:00 [queued]>
[2025-03-30T10:03:16.650+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-30T10:03:16.738+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_aqi_data_Lat_Phrao> on 2025-03-30 10:03:09.568060+00:00
[2025-03-30T10:03:16.780+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=31847) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T10:03:16.787+0000] {standard_task_runner.py:72} INFO - Started process 31858 to run task
[2025-03-30T10:03:16.777+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'get_aqi_data_Lat_Phrao', 'manual__2025-03-30T10:03:09.568060+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpvxd5rem_']
[2025-03-30T10:03:16.788+0000] {standard_task_runner.py:105} INFO - Job 414: Subtask get_aqi_data_Lat_Phrao
[2025-03-30T10:03:16.960+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.get_aqi_data_Lat_Phrao manual__2025-03-30T10:03:09.568060+00:00 [running]> on host 58b9640d9ecf
[2025-03-30T10:03:17.455+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='get_aqi_data_Lat_Phrao' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T10:03:09.568060+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T10:03:09.568060+00:00'
[2025-03-30T10:03:17.456+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T10:03:17.461+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T10:03:17.461+0000] {logging_mixin.py:190} INFO - Current task name:get_aqi_data_Lat_Phrao state:running start_date:2025-03-30 10:03:16.605097+00:00
[2025-03-30T10:03:17.461+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-30T10:03:17.463+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T10:03:18.060+0000] {logging_mixin.py:190} INFO - API URL: https://api.airvisual.com/v2/city?city=Lat_Phrao&state=Bangkok&country=Thailand&key=***
[2025-03-30T10:03:18.066+0000] {logging_mixin.py:190} INFO - Response Status Code: 400
[2025-03-30T10:03:18.067+0000] {logging_mixin.py:190} INFO - Response Text: {"status":"fail","data":{"message":"city_not_found"}}
[2025-03-30T10:03:18.067+0000] {logging_mixin.py:190} INFO - Parsed JSON: {
  "status": "fail",
  "data": {
    "message": "city_not_found"
  }
}
[2025-03-30T10:03:18.075+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T10:03:18.104+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T10:03:18.106+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=get_aqi_data_Lat_Phrao, run_id=manual__2025-03-30T10:03:09.568060+00:00, execution_date=20250330T100309, start_date=20250330T100316, end_date=20250330T100318
[2025-03-30T10:03:18.132+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-30T10:03:18.132+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-30T10:03:18.133+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-30 10:03:09.577745+00:00
[2025-03-30T10:03:18.133+0000] {logging_mixin.py:190} INFO - Task hostname:58b9640d9ecf operator:PythonOperator
[2025-03-30T10:03:18.182+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T10:03:18.256+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T10:03:18.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
