[2025-03-20T09:53:02.226+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T09:53:02.238+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data manual__2025-03-20T09:52:56.382972+00:00 [queued]>
[2025-03-20T09:53:02.244+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data manual__2025-03-20T09:52:56.382972+00:00 [queued]>
[2025-03-20T09:53:02.245+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-20T09:53:02.254+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data> on 2025-03-20 09:52:56.382972+00:00
[2025-03-20T09:53:02.269+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1964) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-20T09:53:02.271+0000] {standard_task_runner.py:72} INFO - Started process 1965 to run task
[2025-03-20T09:53:02.267+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data', 'manual__2025-03-20T09:52:56.382972+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpl3r5y5od']
[2025-03-20T09:53:02.273+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask validate_aqi_data
[2025-03-20T09:53:02.313+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data manual__2025-03-20T09:52:56.382972+00:00 [running]> on host 1a0dfda72c05
[2025-03-20T09:53:02.370+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T09:52:56.382972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T09:52:56.382972+00:00'
[2025-03-20T09:53:02.371+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-20T09:53:02.372+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-20T09:53:02.372+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data state:running start_date:2025-03-20 09:53:02.238789+00:00
[2025-03-20T09:53:02.372+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-20T09:53:02.372+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-20T09:53:02.373+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T09:53:02.379+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-20T09:53:02.380+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data, run_id=manual__2025-03-20T09:52:56.382972+00:00, execution_date=20250320T095256, start_date=20250320T095302, end_date=20250320T095302
[2025-03-20T09:53:02.386+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-20T09:53:02.386+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-20T09:53:02.386+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-20 09:52:56.419808+00:00
[2025-03-20T09:53:02.386+0000] {logging_mixin.py:190} INFO - Task hostname:1a0dfda72c05 operator:PythonOperator
[2025-03-20T09:53:02.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T09:53:02.424+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T09:53:02.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
